### ISSUE TITLE
The run destination My Mac is not valid for Running the scheme 'MachOView'.

### ISSUE THREAD

**Issue by Natoto** [gdbinit/MachOView#8]
xcode cannot run,and show this : "The run destination My Mac is not valid for Running the scheme 'MachOView'. "
why?

**Comment by NSDex** [comment]
Because the Base SDK for the MachOView target is set to macosx10.9.  Change it to Latest Mac OS X and it will build.

**Comment by gdbinit** [comment]
Yes just need to update the build target.
